import { NextResponse } from "next/server";

export async function POST(
  request: Request
) {
  const body =
    await request.json();

  const content = `
LeagueLens AI Report

Player:
${body.playerName}

Role:
${body.role}

Performance Score:
${body.score}

Generated by LeagueLens AI
`;

  return new NextResponse(
    content,
    {
      headers: {
        "Content-Type":
          "application/pdf",
        "Content-Disposition":
          `attachment; filename="${body.playerName}-report.pdf"`,
      },
    }
  );
}